In [1]:
# Importing Data Wrangling Libraries
import pandas as pd
import numpy as np

# Opening the dataset
url = r"/home/youssef/Desktop/Data_Projects/Egypt_Education/Data/egypt_education_dataset.csv"
df = pd.read_csv(url)
df.head()

,Student Name,Student Age,Student year,Father Degree,Mother Degree,Education Type,Subject_1,Subject_2,Subject_3,Subject_4,Subject_5,Subject_6,Subject_7,Subject_8,Subject_9,Subject_10
0,Allison Lang,18,Year 9,High School,High School,IB,72.236740,85.931149,65.698513,84.163844,78.179414,50.578209,70.071681,80.294509,72.709741,59.080678
1,Jaclyn Mcneil,14,Year 9,Bachelor,PhD,IB,91.603078,73.186427,64.240239,47.786542,83.138581,66.913702,42.587211,87.997009,89.176862,78.493158
2,Melissa Lee,16,Year 10,NaN,PhD,IB,100.000000,83.985923,89.378162,82.446853,86.368818,90.347020,100.000000,83.972296,69.212961,79.206634
3,Timothy Maxwell,14,Year 10,Bachelor,Bachelor,Thanweya,91.082131,100.000000,78.802220,78.447670,64.606239,82.045421,69.869099,91.122870,95.207752,52.602706
4,Eric Steele,17,Year 11,PhD,NaN,IGCSE,74.906144,69.518146,65.284841,56.317028,69.758140,85.810641,63.776955,61.802599,84.951132,68.146467

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student Name    50000 non-null  str
 1   Student Age     50000 non-null  int64
 2   Student year    50000 non-null  str
 3   Father Degree   39960 non-null  str
 4   Mother Degree   39910 non-null  str
 5   Education Type  50000 non-null  str
 6   Subject_1       50000 non-null  float64
 7   Subject_2       50000 non-null  float64
 8   Subject_3       50000 non-null  float64
 9   Subject_4       50000 non-null  float64
 10  Subject_5       50000 non-null  float64
 11  Subject_6       50000 non-null  float64
 12  Subject_7       50000 non-null  float64
 13  Subject_8       50000 non-null  float64
 14  Subject_9       50000 non-null  float64
 15  Subject_10      50000 non-null  float64
dtypes: float64(10), int64(1), str(5)
memory usage: 7.8 MB

In [3]:
df.nunique()

Student Name      40111
Student Age           5
Student year          4
Father Degree         4
Mother Degree         4
Education Type        3
Subject_1         47652
Subject_2         47591
Subject_3         47638
Subject_4         47586
Subject_5         47613
Subject_6         47574
Subject_7         47637
Subject_8         47577
Subject_9         47676
Subject_10        47595
dtype: int64

In [4]:
# Making column names more consistent and easier to work with
new_columns = []

for col in df.columns:
    # Replace special characters with spaces
    clean_col = col.replace('-', ' ').replace('/', ' ').replace('.', ' ')
    # Split the cleaned column name into words
    words = clean_col.split()
    #  Capitalize each word and join them with underscores
    new_col = '_'.join(word.capitalize() for word in words)
    new_columns.append(new_col)

# Assign the new column names back to the DataFrame
df.columns = new_columns

In [6]:
# Total number of rows
total_rows = len(df)
print("Total rows:", total_rows)

# Total number of columns
unique_names = df["Student_Name"].nunique()
print("Unique student names:", unique_names)

Total rows: 50000
Unique student names: 40111

In [8]:
# Count the occurrences of each name
name_counts = df["Student_Name"].value_counts()

# Names that appear more than once
duplicates = name_counts[name_counts > 1]
print(duplicates)

Student_Name
Michael Smith          25
Michael Davis          19
Christopher Smith      17
James Smith            17
Michael Johnson        17
                       ..
David Kline             2
Matthew Rios            2
Steven David            2
Christopher Bennett     2
Alexander Hernandez     2
Name: count, Length: 5984, dtype: int64

In [9]:
# Check for fully duplicate rows
duplicate_rows = df[df.duplicated()]
print("Number of fully duplicate rows:", len(duplicate_rows))

Number of fully duplicate rows: 0

In [17]:
# Checking for missing values
df["Father_Degree"] = df["Father_Degree"].fillna("Unknown")
df["Mother_Degree"] = df["Mother_Degree"].fillna("Unknown")

# Extracting numeric part from "Student year" and converting it to integer
df["Student_Year"] = df["Student_Year"].astype(str)
df["Student_Year_num"] = df["Student_Year"].str.extract('(\d+)').astype(int)

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_112804/693904877.py:7: SyntaxWarning: invalid escape sequence '\d'
  df["Student_Year_num"] = df["Student_Year"].str.extract('(\d+)').astype(int)

In [14]:
df.describe()

,Student_Age,Student_Year,Subject_1,Subject_2,Subject_3,Subject_4,Subject_5,Subject_6,Subject_7,Subject_8,Subject_9,Subject_10
count,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,16.00368,10.493500,74.730855,74.697132,74.658231,74.789693,74.610735,74.741407,74.690653,74.734522,74.710284,74.689639
std,1.41582,1.117758,14.345020,14.367525,14.330384,14.366513,14.326871,14.408353,14.348436,14.373802,14.355054,14.365250
min,14.00000,9.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
25%,15.00000,9.000000,64.918132,64.786097,64.870431,64.884569,64.752157,64.837589,64.944466,64.985014,64.977238,64.845485
50%,16.00000,10.000000,75.050027,74.916854,74.959196,75.045955,74.920325,75.083056,74.966657,74.949263,75.033263,74.987325
75%,17.00000,11.000000,85.145231,85.139383,84.972541,85.268959,84.984459,85.208810,85.071789,85.119971,85.152224,85.087438
max,18.00000,12.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [15]:
# Creating new features for total and average scores, and categorizing performance
subjects = [f'Subject_{i}' for i in range(1, 11)]
df["Total_Score"] = df[subjects].sum(axis=1)
df["Average_Score"] = df[subjects].mean(axis=1)

# Function to categorize performance based on average score
def performance_category(avg):
    if avg >= 85: return "Excellent"
    elif avg >= 70: return "Good"
    elif avg >= 50: return "Average"
    else: return "Needs Improvement"

df["Performance"] = df["Average_Score"].apply(performance_category)

In [18]:
# Saving the cleaned dataset for analysis
df_cleaned = df.copy()
df_cleaned.to_csv("/home/youssef/Desktop/Data_Projects/Egypt_Education/Data/education_cleaned.csv", index=False)